version: "3.9"

services:
  database_postgres:
    image: postgres
    container_name: database_postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=mauriciodemoura
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres
    network_mode: "host"

  app:
    build: .
    container_name: rentx
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    network_mode: "host"  


volumes: 
  pgdata:
    driver: local